# Copyright (c) 2026 Data-Blitz Inc. All rights reserved.
# License: Proprietary. See NOTICE.md.
# Author: Paul Harvener.

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: attorneyos-application-logs
    static_configs:
      - targets:
          - localhost
        labels:
          app: attorneyos
          job: deposition-api-logs
          __path__: /var/log/attorneyos/*.log
